### ISSUE TITLE
httpMethod no longer expects a string in TypeScript

### ISSUE THREAD

**Issue by shruggr** [googleapis/nodejs-tasks#331]
In 1.7.0, when creating a new task, I get the following error. It works fine in 1.6.0

```
error TS2322: Type '{ httpRequest: { httpMethod: string; url: string; body: Buffer; headers: { "Content-Type": string; }; }; scheduleTime: { seconds: number; }; }' is not assignable to type 'ITask'.
  The types of 'httpRequest.httpMethod' are incompatible between these types.
    Type 'string' is not assignable to type 'HttpMethod'.
```

#### Environment details

  - OS: Windows 10
  - Node.js version: v12.0.0
  - npm version: 6.9.0
  - `@google-cloud/tasks` version: 1.7.0

#### Steps to reproduce

```
const client = new CloudTasksClient();
const task = {
    httpRequest: {
        httpMethod: 'POST',
        url: EVENT_URL,
        body: Buffer.from(JSON.stringify({a: 1})),
        headers: {
            "Content-Type": "application/json"
        }
    },
    scheduleTime: {
        seconds: delaySeconds + Date.now() / 1000
    }
};
await client.createTask({ parent: QUEUE_PATH, task });
```

**Comment by bcoe** [comment]
@shruggr thanks for the bug report; @xiaozhenliu-gg5, @alexander-fenster looks like potentially a bug with the move to the microgenerator?

**Comment by alexander-fenster** [comment]
@shruggr Yeah, we're aware of this problem. If you had used JavaScript, the `string` would've worked just fine, but in TypeScript, you can't just pass a string to something that is not a string (but is a `enum`).

Right now, there are two ways to solve it:

1. Use a proper `enum`:

```ts
import * as protos from '@google-cloud/tasks/build/protos/protos';

const task = {
  httpRequest: {
    httpMethod: protos.google.cloud.tasks.v2.HttpMethod.POST,
  . . .
};
```

2. Alternatively, you can still use a string, just use the protobuf.js `fromObject`:

```ts
import * as protos from '@google-cloud/tasks/build/protos/protos';

const task = protos.google.cloud.tasks.v2.Task.fromObject({
  httpRequest: {
    httpMethod: 'POST',
  . . .
});
```

I have submitted an issue for the code generator we use, we'll figure out the best way to make it transparent, but until that time, feel free to use one of the above solutions.

**Comment by alexander-fenster** [comment]
This should be fixed in v1.7.3. We updated the types to include all possible string values using `keyof typeof google.cloud.tasks.v2.HttpMethod`, this is the best we could do without breaking existing code.

**Comment by jacksontong** [comment]
I still have this issue in v1.9.0

**Comment by alexander-fenster** [comment]
@jacksontong All `httpMethod` field accept strings in v1.9.0:

```
$ grep version node_modules/\@google-cloud/tasks/package.json 
  "version": "1.9.0"
$ grep httpMethod node_modules/\@google-cloud/tasks/build/protos/protos.d.ts 
                    /** HttpRequest httpMethod */
                    httpMethod?: (google.cloud.tasks.v2.HttpMethod|keyof typeof google.cloud.tasks.v2.HttpMethod|null);
                    /** HttpRequest httpMethod. */
                    public httpMethod: (google.cloud.tasks.v2.HttpMethod|keyof typeof google.cloud.tasks.v2.HttpMethod);
                    /** AppEngineHttpRequest httpMethod */
                    httpMethod?: (google.cloud.tasks.v2.HttpMethod|keyof typeof google.cloud.tasks.v2.HttpMethod|null);
                    /** AppEngineHttpRequest httpMethod. */
                    public httpMethod: (google.cloud.tasks.v2.HttpMethod|keyof typeof google.cloud.tasks.v2.HttpMethod);
                    /** AppEngineHttpRequest httpMethod */
                    httpMethod?: (google.cloud.tasks.v2beta2.HttpMethod|keyof typeof google.cloud.tasks.v2beta2.HttpMethod|null);
                    /** AppEngineHttpRequest httpMethod. */
                    public httpMethod: (google.cloud.tasks.v2beta2.HttpMethod|keyof typeof google.cloud.tasks.v2beta2.HttpMethod);
                    /** HttpRequest httpMethod */
                    httpMethod?: (google.cloud.tasks.v2beta3.HttpMethod|keyof typeof google.cloud.tasks.v2beta3.HttpMethod|null);
                    /** HttpRequest httpMethod. */
                    public httpMethod: (google.cloud.tasks.v2beta3.HttpMethod|keyof typeof google.cloud.tasks.v2beta3.HttpMethod);
                    /** AppEngineHttpRequest httpMethod */
                    httpMethod?: (google.cloud.tasks.v2beta3.HttpMethod|keyof typeof google.cloud.tasks.v2beta3.HttpMethod|null);
                    /** AppEngineHttpRequest httpMethod. */
                    public httpMethod: (google.cloud.tasks.v2beta3.HttpMethod|keyof typeof google.cloud.tasks.v2beta3.HttpMethod);
```

If you still see the error, could you please share your code here? Thank you!

**Comment by jacksontong** [comment]
@alexander-fenster here is the code [https://codesandbox.io/s/cranky-taussig-q5j2q](https://codesandbox.io/s/cranky-taussig-q5j2q)

**Comment by jketcham** [comment]
I ran into this issue and was able to just reference the `POST` type from protos to get around it, but in case this is helpful here is the error I was getting before when I was just using a string `'POST'`:

```
src/tasks.ts:52:30 - error TS2345: Argument of type '{ parent: string; task: { appEngineHttpRequest: { httpMethod: string; relativeUri: string; body: string; }; }; }' is not assignable to parameter of type 'ICreateTaskRequest'.
  The types of 'task.appEngineHttpRequest.httpMethod' are incompatible between these types.
    Type 'string' is not assignable to type '"GET" | "HEAD" | "POST" | "DELETE" | "PUT" | "OPTIONS" | "PATCH" | HttpMethod | "HTTP_METHOD_UNSPECIFIED" | null | undefined'.

52     return client.createTask(request);
```

With code:

```
const parent = ...;

const task = {
  appEngineHttpRequest: {
    httpMethod: 'POST',
    relativeUri: '/index',
    body: Buffer.from(JSON.stringify(indexRequest)).toString('base64'),
  },
};

const request = { parent, task };

return client.createTask(request);
```

I'm on version 2.0.0 of `@google-cloud/tasks`.

**Comment by ottob** [comment]
I ran into the same issue today using v2.1.0.

My code (copied from the js sample):
```ts
const task = {
  httpRequest: {
    httpMethod: 'POST',
    url,
  },
}

const request = { parent, task }
const [response] = await client.createTask(request)
```
Error:
```
Argument of type '{ parent: string; task: { httpRequest: { httpMethod: string; url: string; body: string | null; }; scheduleTime: { seconds: number; }; }; }' is not assignable to parameter of type 'ICreateTaskRequest'.
  The types of 'task.httpRequest.httpMethod' are incompatible between these types.
    Type 'string' is not assignable to type '"POST" | HttpMethod | "HTTP_METHOD_UNSPECIFIED" | "GET" | "HEAD" | "PUT" | "DELETE" | "PATCH" | "OPTIONS" | null | undefined'.ts(2345)
```

**Comment by alexander-fenster** [comment]
OK, I see the problem now. The auto-inferred type for `task` has `httpRequest: string` and even though the _value_ you're going to assign matches the type, the type checked gets mad.

I guess you could make the sample work by writing `const task = { ..... } as protos.google.cloud.tasks.v2.CreateTaskRequest;` but that's ugly too. Thank you folks for reporting this, we'll think how to deal with this properly.

**Comment by bzuker** [comment]
I also ran into this issue recently, has this been fixed or does it need to be reopened? Maybe exposing the `enum` could be a possibility?

**Comment by rconjoe** [comment]
Same problem here:

Version: 2.3.2
Task: HTTP

`const task = protos.google.cloud.tasks.v2beta3.Task.fromObject(<our-task-here>)` ended up working for us. I also tried typing just the `'POST'` field with the HttpMethod proto and still got the type error. The only solution was to use `fromObject`.

**Comment by rconjoe** [comment]
We had the same issue in 2.3.2. @alexander-fenster's solution to use `fromObject` quelled tsc complaints but when running the function would return an error: 
`TypeError: this.constructor.toObject is not a function`

What ended up working for us was explicitly typing the `task` object to be sent to `client.createTask()` using the `Itask` properties found in `proto.google.cloud.tasks.v2beta3.Itask`.

**Comment by tomhoad** [comment]
Still an issue as of `2.4.2`.

The basic 'Getting Started' won't work with TS without directly importing the `protos` and using the enum directly.

**Comment by Stf-F** [comment]
Just bumped into this today with `2.5.0` and importing protos did do the trick. 👍

**Comment by MorenoMdz** [comment]
> ```ts
> protos.google.cloud.tasks.v2.HttpMethod.POST
> ```

Why is this issue closed? It is not clear that we need to use `protos.google.cloud.tasks.v2.HttpMethod.POST`, the documentation should be more clear and/or simply accept a string ENUM.

**Comment by alexander-fenster** [comment]
@MorenoMdz It should accept a string enum value. The type definition uses `keyof typeof` so strings should be accepted, and on `protobufjs` side, string enum values are also accepted. Does it not work for you? Please share your code :)

**Comment by MorenoMdz** [comment]
> keyof

We are using version 3.0.0, this works:

```js
    const task = {
      httpRequest: {
        httpMethod: protos.google.cloud.tasks.v2.HttpMethod.POST,
        url: functionUrl,
        oidcToken: {
          serviceAccountEmail,
          audience: new URL(functionUrl).origin
        },
        headers: {
          "Content-Type": "application/json",
          ...headers
        },
        body
      },
      scheduleTime: { seconds: targetTimeInSeconds }
    };
 ```
 
 But `httpMethod: "POST"` does not.
 
 
![image](https://user-images.githubusercontent.com/29472480/178857383-504c8399-a3fb-429b-b8ba-178a3bcebda1.png)

**Comment by alexander-fenster** [comment]
This is not the library problem, but the problem with how TypeScript guesses the type of the `httpRequest` field. Since you have `const task = { httpRequest: 'POST' }`, TypeScript decides that the type of the `task` variable is `{ httpRequest: string }`, which cannot be be used in the API request because it expects `{ httpRequest: 'POST' | 'GET' | ... }`. We could've solved this by making the parameter accept any `string` instead of `keyof typeof ...`, but then we would've lost all compile time checks for the string enum values.

You can do the following to tell TypeScript compiler that the type of the `task` is `ITask`:

```ts
import {CloudTasksClient, protos} from '@google-cloud/tasks';

...

    const task: protos.google.cloud.tasks.v2.ITask = {
      appEngineHttpRequest: {
        httpMethod: 'POST',
        relativeUri: '/log_payload',
      },
    };
```

and then it will understand that `httpRequest` is of type `POST` | `GET` | ... and will happily pass it to the API.

Since our samples are in JavaScript and not in TypeScript, sometimes (in cases like this one) they cannot be easily copy-pasted to the TypeScript code. I took [`samples/quickstart.js`](https://github.com/googleapis/nodejs-tasks/blob/main/samples/quickstart.js) and made it compile in TypeScript by adding type information here and there: [gist](https://gist.github.com/alexander-fenster/832dcdaf46f1e21f5d3ea337266c7778)

I hope that helps!
